line-length = 120

[lint]
extend-select = [
    "ARG",
    "B",
    "C",
    "DTZ",
    "E",
    "EM",
    "F",
    "FBT",
    "I",
    "ICN",
    "ISC",
    "N",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "Q",
    "RUF",
    "S",
    "T",
    "TID",
    "UP",
    "W",
    "YTT",
]

ignore = [
    # Manage quotes with formatter
    "Q000",
    # Allow non-abstract empty methods in abstract base classes
    "B027",
    # Allow boolean positional values in function calls, like `dict.get(... True)`
    "FBT003",
    # Ignore checks for possible passwords
    "S105",
    "S106",
    "S107",
    # Ignore complexity
    "C901",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0915",
]
exclude = ["*.ipynb"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = [
    # Don't touch unused imports
    "F401",
]

[lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files, and in selected subdirectories.
"__init__.py" = ["E402", "F403", "F405"]
"**/{tests,docs,tools}/*" = ["E402", "PLR2004", "S101", "TID252"]

[format]
quote-style = "single"
exclude = ["*.ipynb"]

[lint.pylint]
max-args = 10

[isort]
known-first-party = ["attractor_explorer"]

[flake8-tidy-imports]
ban-relative-imports = "all"
